class UserIdentity:
    QUISHOP_STAFF = "QUISHOP_STAFF"
    TENANT_STAFF = "TENANT_STAFF"
    CUSTOMER = "CUSTOMER"
    CHOICES = [
        (QUISHOP_STAFF, QUISHOP_STAFF),
        (TENANT_STAFF, TENANT_STAFF),
        (CUSTOMER, CUSTOMER),
    ]
